[pytest]
pythonpath = src
testpaths = tests
addopts = --strict-markers
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    model: test the model loading and correctness
    data: tests dataset loading and dataloaders
    training: tests training loops and training preparations
    loadingsaving: tests to check loading and saving training state

